// import styles from "../styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { signIn, getSession } from "next-auth/react";
import Breadcrumb from "@components/ui/breadcrumb";
import { Col, Container, Row } from "react-bootstrap";
import { HeaderOne as Header } from "@components/header";
import { FooterOne as Footer } from "@components/footer";
import { HomePagesNavData as navContent } from "@data/navbar";
import { ContentWrapperOne as ContentWrapper } from "@components/wrapper";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import cogoToast from "cogo-toast";
import ReactLoading from 'react-loading';


const loginValidationSchema = yup.object().shape({
  email: yup
    .string()
    .email("Must be an Email")
    .required("Email is required")
    .lowercase(),
  password: yup.string().required("Password is required"),
});

export default function Login() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: yupResolver(loginValidationSchema),
  });
  const logo = "/assets/images/no-placeholder/logo.png";

  useEffect(() => {
    getSession().then((session) => {
      if (session) {
        router.replace("/");
      } else {
      }
    });
  }, []);

  const login = async (validatedValues) => {
    const { email, password } = validatedValues;
    setIsLoading(true);
    try {
      const res = await signIn("credentials", {
        redirect: false,
        email: email,
        password: password,
      });
      if (res.error) {
        cogoToast.success("Password or Email is incorrect", { hideAfter: 3 });
      }
      router.push("/admin-dashboard");
    } catch (err) {
      console.log("ERROR", err);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="">


      <Head>
        <title>Pricesure Admin login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header
        logo={logo}
        navbar={true}
        navData={navContent}
        navbarAlignment="left"
      /> */}

      <ContentWrapper>
        <Breadcrumb />

        <div className="container-indent">
          <Container>
            <h1 className="tt-title-subpages noborder">ALREADY REGISTERED?</h1>
            <div className="tt-login-form">
              <Row>
                <Col md={6}>
                  <div className="tt-item">
                    <h2 className="tt-title">NEW CUSTOMER</h2>
                    <p>
                      By creating an account with our store, you will be able to
                      move through the checkout process faster, store multiple
                      shipping addresses, view and track your orders in your
                      account and more.
                    </p>
                    <div className="form-group">
                      <Link href="/register">
                        <a className="btn btn-top btn-border">
                          CREATE AN ACCOUNT
                        </a>
                      </Link>
                    </div>
                  </div>
                </Col>

                <Col md={6}>
                  <div className="tt-item">
                    <h2 className="tt-title">LOGIN</h2>
                    <p>If you have an account with us, please log in.</p>
                    <div className="form-default form-top">
                      <form id="customer_login">
                        <div className="form-group">
                          <label htmlFor="loginUserName">E-MAIL *</label>
                          <div className="tt-required">* Required Fields</div>
                          <input
                            type="email"
                            id="loginUserName"
                            className="form-control border"
                            placeholder="Enter E-mail"
                            {...register("email")}
                          />
                          <p className="mt-1 ml-4 text-danger text-sm">
                            {errors.email?.message}
                          </p>
                        </div>
                        <div className="form-group">
                          <label htmlFor="loginPassword">PASSWORD *</label>
                          <input
                            type="password"
                            id="loginPassword"
                            className="form-control border"
                            placeholder="Enter Password"
                            {...register("password")}
                          />
                          <p className="mt-1 ml-4 text-danger text-sm">
                            {errors.password?.message}
                          </p>
                        </div>
                        <Row>
                          <Col xs="auto" className="mr-auto">
                            <div className="form-group">
                              <button
                                style={styles.loginBtn}
                                // className="btn-primary"
                                onClick={handleSubmit(login)}
                              >
                                LOGIN
                                {
                                  isLoading &&
                                  <div style={{ paddingLeft: "5px" }}>
                                    <ReactLoading type={"spin"} color={"#0d6efd"} height={20} width={20} />
                                  </div>
                                }
                              </button>
                            </div>
                          </Col>
                          <Col xs="auto" className="align-self-center">
                            <div className="form-group ">
                              <ul className="additional-links">
                                <li>
                                  <Link href="/account/register">
                                    Lost your password?
                                  </Link>
                                </li>
                              </ul>
                            </div>
                          </Col>
                        </Row>
                      </form>
                    </div>
                  </div>
                </Col>
              </Row>
            </div>
          </Container>
        </div>
      </ContentWrapper>
      <Footer logo={logo} />
    </div>
  );
}

const styles = {
  loginBtn: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 5,
    paddingBottom: 5,
    background: "none",
    color: "#0d6efd",
    border: "2px solid #0d6efd",
    display: "flex",
    justifyContent: "center",
    alignItems: "center"
  },
};
